### ISSUE TITLE
Moodle 3.11 will require change to user fields

### ISSUE THREAD

**Issue by cladelpino** [catalyst/moodle-tool_trigger#155] opened 2021-10-20 17:09 UTC
Fields  icq,aim,msn,url,yahoo,skype were "deprecated" in Moodle 3.11, and they are hard-coded in this plugin in user_lookup_step.php 

For a quick fix, comment them out from the $stepfields array.

**Comment by dmitriim** [comment] 2022-03-06 23:43
Duplicate of https://github.com/catalyst/moodle-tool_trigger/issues/144

**Closed by dmitriim** 2022-03-06 23:43 UTC

**Comment by JoaoCaldasCosta** [comment] 2022-04-28 12:58
> Fields icq,aim,msn,url,yahoo,skype were "deprecated" in Moodle 3.11, and they are hard-coded in this plugin in user_lookup_step.php
> 
> For a quick fix, comment them out from the $stepfields array.

How/where can I do this?
I am trying to put this to work and I can do the course lookup but I always get an error on the user lookup, I suppose it is the same issue you reported

**Comment by dmitriim** [comment] 2022-04-28 23:20
@JoaoCaldasCosta  please switch to MOODLE_311_STABLE branch. The issue has been fixed there.
