### ISSUE TITLE
Workflow doesnt work

### ISSUE THREAD

**Issue by light5551** [catalyst/moodle-tool_trigger#109] opened 2020-06-30 12:19 UTC
Hi! After instalation i created workflow, but trigger doesnt work. I tried differents events, but without any results.
![image](https://user-images.githubusercontent.com/31547459/86124391-bd084600-bae3-11ea-9c1e-485041480885.png)
![image](https://user-images.githubusercontent.com/31547459/86124409-c42f5400-bae3-11ea-9aa1-6d65c0ffb402.png)

`version download`: `2018102100`
`moodle version`: `3.8.2`

What am i doing wrong? 

P.S. I tried samples for workflow from your repository, just change event. The same result - dont work
Thanks

**Comment by lockerob** [comment] 2020-07-17 15:45
I am having the same problem as well. I followed all the guides I could find with the same result. Nothing. I would love to find out what we are doing wrong!

**Comment by Peterburnett** [comment] 2020-07-27 04:35
Hi @light5551 
I note your version number for Trigger is an older one. What happens if you upgrade to the latest master code?

**Comment by Peterburnett** [comment] 2020-07-29 22:45
Also, is cron running regularly on your site? These events are processed every minute (by default) using a scheduled task

**Comment by mattporritt** [comment] 2021-03-04 01:26
closing could not reproduce

**Closed by mattporritt** 2021-03-04 01:26 UTC
