### ISSUE TITLE
Core update issue

### ISSUE THREAD

**Issue by bjimenez-lallemand** [catalyst/moodle-tool_trigger#46] opened 2018-10-15 16:49 UTC
I created a workflow associated with the '**Core: User password updated**' event. It works but if i modify the event, it stops working. I have to erase it and recreate it in order for it to work again.

Thanks

**Comment by mattporritt** [comment] 2018-10-16 20:20
Hi,
Thanks for reporting this. We’ll look into it. Are you able to let me know what version of Moodle you are using?

**Comment by bjimenez-lallemand** [comment] 2018-10-17 13:15
Hello

Of course, i'm using Moodle 3.5.2+ (Build: 20181011) Version 2018051702.06. Just in case it's relevant, i created a simple event with the same steps but associated to the "**Core: User has logged in**" event, and it works like a charm. Both have a user lookup and an email to the user with a simple message.

Thanks

**Comment by mattporritt** [comment] 2018-10-18 23:29
Hi,
It is strange that it works for one event but not the other. But thanks for the extra information it will make it easier to track down.

Cheers

**Comment by mattporritt** [comment] 2018-10-21 06:40
I haven't been able to reproduce this. 
I've created an event that is triggered by the 'Core: User password updated' and tested it.  The workflow is triggered when a user password is updated. It also continues to work when I update the workflow.

The only thing I did discover is that if you update a users password, the workflow will trigger. But if you update a users password and set it to the same password as the previous password the Moodle event doesn't fire and so the workflow doesn't trigger.  It seems the Moodle update password event only works if you, change a users password to a different value.

I've attached the workflow I was using to test this ticket.  It is setup to dump the workflow result to the cron log.  I was triggering the workflow processing scheduled task directly from the command line using: `php admin/tool/task/cli/schedule_task.php --execute='\tool_trigger\task\process_workflows'

[password_update_test_20181021_0637.json.zip](https://github.com/catalyst/moodle-tool_trigger/files/2498857/password_update_test_20181021_0637.json.zip)

**Comment by bjimenez-lallemand** [comment] 2018-10-22 13:36
Hello Matt:
I found out the same thing as you did (regarding the update to the same password). I will test using your workflow and let you know my results.

Regards
Brandon

**Comment by bjimenez-lallemand** [comment] 2018-11-06 15:05
The first step, the number comparison, is just to make sure it only gets triggered with your userid in your installation, right?

**Comment by bjimenez-lallemand** [comment] 2018-11-06 15:49
so after a few rounds of testing, it didn't work for me. I'm attaching my own workflow in case you want to test it
[Password_update_20181106_1548.zip](https://github.com/catalyst/moodle-tool_trigger/files/2553870/Password_update_20181106_1548.zip)

**Comment by mattporritt** [comment] 2021-03-04 01:20
closing could not reproduce

**Closed by mattporritt** 2021-03-04 01:20 UTC
