### ISSUE TITLE
Cleanup task fails on MySQL

### ISSUE THREAD

**Issue by peterspicer-catalyst** [catalyst/moodle-tool_trigger#121] opened 2020-11-12 14:35 UTC
Client server: `Server version: 5.6.47.0 MySQL Community Server (GPL)`

The cleanup task has this query:

```
        $sql = "
            DELETE
              FROM {tool_trigger_events} e
             WHERE NOT EXISTS (
                       SELECT 1
                         FROM {tool_trigger_queue} q
                        WHERE q.eventid = e.id
                              AND q.status = :statusready
                   )
                   AND e.timecreated < :timetocleanup";
```

Unfortunately on MySQL this looks like it fails with a syntax error because you can't do DELETE FROM table alias WHERE (stuff with alias) - the same thing works fine written as a SELECT * FROM ... instead, but MySQL's behaviour of multi-table deleting is a bit weird and I think also maybe version dependent. (As in, this probably works fine in MySQL 5.7)

Off the top of my head I'm thinking:

```
        $sql = "
            DELETE
              FROM {tool_trigger_events}
             WHERE id IN (
                       SELECT id from {tool_trigger_events} e
                        WHERE NOT EXISTS (
                           SELECT 1
                             FROM {tool_trigger_queue} q
                            WHERE q.eventid = e.id
                                  AND q.status = :statusready

                        )
                          AND e.timecreated < :timetocleanup
                    )";
```

Would appreciate some insight.

**Comment by durzo** [comment] 2021-02-17 13:16
task cleanup_history is also failing on the same thing:

```
Execute scheduled task: Delete historical trigger data (tool_trigger\task\cleanup_history)
... started 07:13:02. Current memory use 14.2MB.
... used 1 dbqueries
... used 0.0050170421600342 seconds
Scheduled task failed: Delete historical trigger data (tool_trigger\task\cleanup_history),Error al escribir a la base de datos (You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rh
                      WHERE rh.executed < '1612962782'
                   ...' at line 1
DELETE FROM mdl_tool_trigger_run_hist rh
                      WHERE rh.executed < ?
                        AND (
                            SELECT COUNT(id) as count
                              FROM mdl_tool_trigger_run_hist sub
                             WHERE sub.runid = rh.runid
                               AND sub.executed > ?
                            ) = 0
[array (
  0 => 1612962782,
  1 => 1612962782,
)])
Debug info:
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rh
                      WHERE rh.executed < '1612962782'
                   ...' at line 1
DELETE FROM mdl_tool_trigger_run_hist rh
                      WHERE rh.executed < ?
                        AND (
                            SELECT COUNT(id) as count
                              FROM mdl_tool_trigger_run_hist sub
                             WHERE sub.runid = rh.runid
                               AND sub.executed > ?
                            ) = 0
[array (
  0 => 1612962782,
  1 => 1612962782,
)]
Backtrace:
* line 1167 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
* line 66 of /admin/tool/trigger/classes/task/cleanup_history.php: call to mysqli_native_moodle_database->execute()
* line 253 of /lib/cronlib.php: call to tool_trigger\task\cleanup_history->execute()
* line 167 of /admin/cli/scheduled_task.php: call to cron_run_inner_scheduled_task()
```

**Comment by marinaglancy** [comment] 2021-02-18 13:07
The solution suggested by the reporter will not work because you can't use the same table in the subquery in mysql:

    [HY000][1093] You can't specify target table 'mdl_tool_trigger_events' for update in FROM clause

MySQL allows to delete from the aliased tables by specifying the alias after the word DELETE:

    DELETE e
    FROM mdl_tool_trigger_events e
    WHERE ....

But postgres does not want to see table alias there.

So you basically have three options:
1. rewrite the function so it has a SELECT and then just delete by ids (this is what core normally does)
2. have some complex code that checks the current database driver and changes the query
3. rewrite the query so it does not have alias, for example:

```
DELETE
FROM {tool_trigger_events}
WHERE NOT EXISTS (
    SELECT 1
    FROM {tool_trigger_queue} q
    WHERE q.eventid = {tool_trigger_events}.id
  AND q.status = :statusready
    )
  AND timecreated < :timetocleanup
```

The second query can be changed similarly too

**Comment by marinaglancy** [comment] 2021-02-18 13:11
Forgot to mention, my mysql version is much higher and I can't even reproduce the original problem so it is possible that my solution will not work on the 5.6.47.0 - please test

**Comment by durzo** [comment] 2021-02-19 10:41
The patch above from @marinaglancy solves the issue for us, currently in production without issue.
I am unable to create a PR (no permission error)

**Comment by mattporritt** [comment] 2021-03-04 01:19
Fixed in latest master

**Closed by mattporritt** 2021-03-04 01:19 UTC

**Comment by durzo** [comment] 2021-03-04 07:36
@mattporritt there are 2 helper tasks that needed fixing for mysql but your commit only addressed one.

Reading the comments above I realise i didn't make that clear, though are fixed in @marinaglancy's branch. my bad!

**Comment by durzo** [comment] 2021-03-04 08:22
submitted PR #125
